### ISSUE TITLE
Servoblaster & virtualenv 

### ISSUE THREAD

**Issue by BBCBasic** [SMalicoat/servoblaster#1]
Hi I'm trying to get Servoblaster & virtualenv working together, and I can't.

Is this possible, if so how?

Cheers Rob

**Comment by SMalicoat** [comment]
Sorry i am not familiar with virtualenv i am not sure how or if it is possible. Sorry

**Comment by BBCBasic** [comment]
Thanks I got it to work. I had to install it outside the virtual environment

Sent from my Phone

On 1 Dec 2016, at 01:18, Sam Malicoat <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry i am not familiar with virtualenv i am not sure how or if it is possible. Sorry

-

**Comment by BBCBasic** [comment]
Thanks I got it to work. I had to install it outside the virtual environment
